### PR TITLE
Adding GitHub action for publishing to PyPi

### PR DESCRIPTION
**Pull request by aarons20**
-[ADDED] GitHub action for publishing python package to PyPi
-[CHANGED] Formatting python code with black (PEP 8)

### CODE REVIEW

**Comment by aarons20** [comment]
This pull request adds support for building and publishing the updated python package to PyPi.

Before merging, the GitHub action needs permission to publish to PyPi. With Trusted Publisher Management you can add this permission at the PyPi website under your projects > manage > publish.

Let me know if you need any further information. If you have any other comments feel free to suggest changes.

image

**Comment by christo-ph** [comment]
This worked like a charm, thank you very much @aarons20

**Comment by christo-ph** [comment]
Might have to add tagging in git as well, as it does now not reflect the same state in repo and pypi

**Comment by aarons20** [comment]
Great to hear that it worked right away🎉

I could also have a look at the tagging topic if you want. Just didn't want to have too much new pipeline stuff in one PR as debugging it is pretty hard without trying on the actual branch.

**Pull request merged**
